## Este es el paso a paso para principiantes

Comenzamos importando la libreria de pandas

In [4]:
import pandas as pd
pd.set_option('display.max_colwidth', None) #Esto es para poder ver todo el texto en una columna

Cargamos el dataset que utilizaremos durante la investigacion

In [6]:
crime_scene_report     = pd.read_csv("./datasets/Crime Scene report.csv")
drivers_license        = pd.read_csv("./datasets/Drivers license.csv")
facebook_event_checkin = pd.read_csv("./datasets/facebook_event_checkin.csv")
getfitnow_checkin      = pd.read_csv("./datasets/GetFitNow check in.csv")
getfitnow_members      = pd.read_csv("./datasets/GetFitNow members.csv")
income                 = pd.read_csv("./datasets/income.csv")
interview              = pd.read_csv("./datasets/Interviews.csv")
person                 = pd.read_csv("./datasets/Person.csv")

Veamos un poco como estan conformados estos dataframes

In [7]:
# Usamos .info() para ver una descripcion general del dataset, como sus tipos de datos en cada columna y si presenta nulos
crime_scene_report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1228 entries, 0 to 1227
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Date         1228 non-null   object
 1   Type         1228 non-null   object
 2   Description  939 non-null    object
 3   City         1228 non-null   object
dtypes: object(4)
memory usage: 38.5+ KB


Con la funcion *.head*(n:int default=5) podemos visualizar las primeras n filas 

In [8]:
crime_scene_report.head(3)

Date       Type Description        City
0  2017-01-07  smuggling         NaN    Savannah
1  2017-01-11     murder         NaN  Springdale
2  2017-01-12  smuggling         NaN   Melbourne

Algunas funciones **utiles** que podrian ayudarte en el proceso:
1. **_`.sort_values()`_**: Esta función se utiliza para ordenar un DataFrame o una Serie según los valores de una o más columnas. Se puede especificar el orden ascendente o descendente. Es útil para organizar los datos de manera coherente y facilitar la búsqueda o el análisis de patrones.

2. **_`.str.contains()`_**: Esta función se utiliza para buscar patrones de texto en una Serie. Permite verificar si una cadena de caracteres contiene un patrón específico. Es útil para realizar filtrados basados en patrones de texto, como buscar palabras clave en un conjunto de datos.

3. **_`.groupby()`_**: Esta función se utiliza para agrupar los datos según una o más columnas en un DataFrame. Se puede combinar con otras funciones de agregación, como _`.sum()`_, _`.mean()`_, _`.count()`_, etc., para realizar cálculos en los grupos resultantes. Es útil para realizar análisis estadísticos o resúmenes de datos basados en categorías.

4. **_`.merge()`_**: Esta función se utiliza para combinar dos DataFrames en función de una o más columnas comunes. Puede realizar una unión interna (inner join), una unión externa (outer join), una unión izquierda (left join) o una unión derecha (right join), según los datos que se deseen mantener. Es útil para combinar conjuntos de datos relacionados en un solo DataFrame para su análisis

5. **_`.isin()`_**: Esta función se utiliza para verificar si los valores de una columna o Serie están presentes en una lista de valores específica.

## `Comenzamos la investigacion`

### Un crimen ha ocurrido y el detective necesita tu ayuda. 


#### Pero antes, veamos un diagrama de esquema para ver como estan conectados todos los dataframes

<img src="./_src/schemeboard.png">


### Te entregaron el informe del lugar del crimen, pero de alguna manera lo perdiste. Recordas vagamente que el crimen fue un ​asesinato​ que ocurrió en algún momento el ​15 de enero de 2018​ y que tuvo lugar en ​Pandas City​. **Te recomiendo comenzar por recuperar el informe correspondiente de su respectivo dataframe**

Vamos a empezar viendo los asesinatos (_murder_) que ocurrieron en la fecha 2018-01-15 (_15 de enero de 2018_) en el dataset `crime_scene_report`

In [9]:
# Hay varias maneras de seleccionar una fila en especifico. Una de ellas es la siguiente:
informe = crime_scene_report[(crime_scene_report["Date"] == "2018-01-15") & 
                            (crime_scene_report["Type"] == "murder")]
informe

Date    Type  \
674  2018-01-15  murder   
675  2018-01-15  murder   
781  2018-01-15  murder   

                                                                                                                                                                                   Description  \
674                                                                                                                                                          Life? Dont talk to me about life.   
675                                                                                                                                        Mama, I killed a man, put a gun against his head...   
781  Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".   

            City  
674       Albany  
675         Reno  
781  Pandas City

Podemos ver que ocurrieron 3 asesinatos en la misma fecha pero en distintas ciudades, ¿se te ocurre alguna manera de modificar el codigo tal que aparezca solamente la que nos interesa para el caso?

In [10]:
# Ubicacion exacta del reporte del asesinato
informe = crime_scene_report[(crime_scene_report["Date"] == "2018-01-15") & 
                            (crime_scene_report["Type"] == "murder") & 
                            (crime_scene_report["City"] == "Pandas City")]
informe

Date    Type  \
781  2018-01-15  murder   

                                                                                                                                                                                   Description  \
781  Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".   

            City  
781  Pandas City

Una vez que tenemos el informe, leemos que dice la descripcion y vemos que hay 2 testigos. Es tu turno de hacer un codigo de tal manera que puedas encontrar a uno o ambos de ellos

_Ayudita:_ usar el dataset `person` y la funcion _df`.str.contains() `_

**_Determinamos el primer testigo que vive en la ultima casa de Northwestern Dr_**

In [11]:
person[(person["Address_Street_Name"]=="Northwestern Dr")].sort_values("Address_Number", ascending=False).head(1)

Id            Name  License_Id  Address_Number Address_Street_Name  \
499  14887  Morty Schapiro      118009            4919     Northwestern Dr   

           Ssn  
499  111564949

**_Determinamos el Segundo testigo de nombre Annabel y vive en Franklin Ave_**

In [12]:
# Determinamos el Segundo testigo de nombre Annabel y viven en Franklin Ave
person[(person["Name"].str.contains("Annabel")) & (person["Address_Street_Name"]=="Franklin Ave")]

Id            Name  License_Id  Address_Number Address_Street_Name  \
665  16371  Annabel Miller      490173             103        Franklin Ave   

           Ssn  
665  318771143

Una vez que encontraste a los testigos en la base de datos de personas, te recomiendo que busques sus entrevistas en el dataset `interviews`

A partir de aca, te dejo el resto de la investigacion a vos. ***¡Muchos exitos detective!***

**_Obtenemos la declaracion de los dos testigos con Id 14887(Primer Testigo) y 16371 (Segundo Testigo)_**

In [18]:
interview[(interview["Person_Id"].isin([16371, 14887]))]

Person_Id  \
4988      14887   
4989      16371   

                                                                                                                                                                                                                           Transcript  
4988  I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".  
4989                                                                                                            I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.

**_Segun informacion de los testigos buscamos quien fue al gym el 09/01 y su codigo de membresia inicie con 48Z_**

In [19]:
getfitnow_checkin[(getfitnow_checkin["Check_In_Date"].str.contains("01-09")) & (getfitnow_checkin["Membership_Id"].str.contains("48Z"))]

Membership_Id Check_In_Date  Check_In_Time  Check_Out_Time
2700         48Z7A    2018-01-09           1600            1730
2701         48Z55    2018-01-09           1530            1700

**_Con la informacion anterior se encontro informacion de dos posibles sospechosos cuyo codigo de membresia sea 48Z7A y 48Z55_**

**_Ahora del dataset de getfitnow_members busco los que su matricula comienza con 48Z y tenga membresia Gold_**

In [20]:
getfitnow_members.rename(columns={"Id":"Membership_Id"}, inplace=True)
getfitnow_members[(getfitnow_members["Membership_Id"].str.contains("48Z")) & (getfitnow_members["Membership_Status"]=="Gold")]

Membership_Id  Person_Id           Name Membership_Start_Date  \
65         48Z7A      28819   Joe Germuska            2016-03-05   
66         48Z55      67318  Jeremy Bowers            2016-01-01   

   Membership_Status  
65              Gold  
66              Gold

**_Igual que la consulta anterior tambien no proporciona informacion de los mismos sospechosos con codigo de membresia 48Z7A y 48Z55_**

**_Consultamos al dataset drivers_license para obtener las personas que su placa incluya "H42W_**"

In [21]:
drivers_license.rename(columns={"Id":"License_Id"}, inplace=True)
drivers_license[(drivers_license["Plate_Number"].str.contains("H42W"))]

License_Id  Age  Height Eye_Color Hair_Color  Gender Plate_Number  \
204       423327   30      70     brown      Brown    Male       0H42W2   
2195      183779   21      65      blue     Blonde  Female       H42W0X   
5693      664760   21      71     black      Black    Male       4H42WR   

       Car_Make Car_Model  
204   Chevrolet  Spark LS  
2195     Toyota     Prius  
5693     Nissan    Altima

**_Nos retorna 3 psoibles sospechosos, realizamos un merge entre el dataset "person" y "drivers_license" para obtener la informacion de las personas_**

In [22]:
# Realizamos un merge del dataset person y drivers_license para encontrar las personas que el numero de su placa incluya "H42W"
df_sospechoso = person.merge(drivers_license[["License_Id", "Plate_Number"]], on=["License_Id"])
df_sospechoso.rename(columns={"Id":"Person_Id"}, inplace=True)
df_sospechoso = df_sospechoso[(df_sospechoso["Plate_Number"].str.contains("H42W"))]
df_sospechoso

Person_Id            Name  License_Id  Address_Number  \
4660      51739  Tushar Chandra      664760             312   
6323      67318   Jeremy Bowers      423327             530   
7574      78193  Maxine Whitely      183779             110   

        Address_Street_Name        Ssn Plate_Number  
4660                 Phi St  137882671       4H42WR  
6323  Washington Pl, Apt 3A  871539279       0H42W2  
7574                Fisk Rd  137882671       H42W0X

**_Se obtuvo como resultado 3 posibles sospechosos, como siguiente realizamos un merge entre el dataset anterior y "getfitnow_members"_**

In [23]:
df_sospechoso = df_sospechoso.merge(getfitnow_members[["Membership_Id", "Person_Id", "Membership_Status"]], on=["Person_Id"])
df_sospechoso

Person_Id           Name  License_Id  Address_Number  \
0      67318  Jeremy Bowers      423327             530   

     Address_Street_Name        Ssn Plate_Number Membership_Id  \
0  Washington Pl, Apt 3A  871539279       0H42W2         48Z55   

  Membership_Status  
0              Gold

**_Como resultado nos retorna la informacion del sospechoso cuyo nombre es "Jeremy Bowers"_**

### Si crees que encontraste al asesino, ejecutá el siguiente codigo con el posible sospechoso
Por favor, tene en cuenta que es recomendable no acceder al archivo "asesino.py" para evitar revelar detalles importantes de la caso. Si deseas disfrutar plenamente de la experiencia sin spoilers, te sugiero que evites examinar dicho archivo."

In [1]:
from asesino import solucion
#solucion("Colocar aca el nombre del sospechoso")
solucion("Jeremy Bowers")

¡Felicidades, encontraste al asesino! Pero espera, hay más...
 Si crees que estas preparado para un desafío, segui investigando 
 la transcripcion del asesino para encontrar al verdadero villano detrás de este crimen


### **_Lamentablmente no es el verdadero villano :(, ahora tendremos que consultar la declaracion de "Jeremy Bowers"_ con id 67318**

In [13]:
interview[(interview["Person_Id"].isin([67318]))]

Person_Id  \
4990      67318   

                                                                                                                                                                                                                                            Transcript  
4990  I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.

**_En el dataset "facebook_event_checkin" buscamos quienes fueron al concierto "SQL Symphony Concert" en Diciembre 2017_**

In [14]:
#facebook_event_checkin.info()
#facebook_event_checkin.head(3)
df_facebook = facebook_event_checkin[(facebook_event_checkin["date"]>=20171201) & (facebook_event_checkin["date"]<=20171231) & (facebook_event_checkin["event_name"]=="SQL Symphony Concert")]
df_facebook

person_id  event_id            event_name      date
4087       62596      1143  SQL Symphony Concert  20171225
4392       19260      1143  SQL Symphony Concert  20171214
6552       58898      1143  SQL Symphony Concert  20171220
6620       69699      1143  SQL Symphony Concert  20171214
6717       19292      1143  SQL Symphony Concert  20171213
7266       43366      1143  SQL Symphony Concert  20171207
8395       92343      1143  SQL Symphony Concert  20171212
10909      28582      1143  SQL Symphony Concert  20171220
10910      28582      1143  SQL Symphony Concert  20171215
13719      81526      1143  SQL Symphony Concert  20171202
13745      24397      1143  SQL Symphony Concert  20171208
14312      11173      1143  SQL Symphony Concert  20171223
15305      79312      1143  SQL Symphony Concert  20171203
15896      69325      1143  SQL Symphony Concert  20171206
20001      24556      1143  SQL Symphony Concert  20171207
20002      24556      1143  SQL Symphony Concert  20171221
20003      24556      1143  SQL Symphony Concert  20171224
20006      99716      1143  SQL Symphony Concert  20171206
20007      99716      1143  SQL Symphony Concert  20171212
20008      99716      1143  SQL Symphony Concert  20171229
20010      67318      1143  SQL Symphony Concert  20171206

**_Buscamos en el dataset "drivers_license" los que cumplen con las caracteristicas indicadas_**

In [26]:
df_license = drivers_license[(drivers_license["Hair_Color"]=="Red") & (drivers_license["Car_Make"]=="Tesla") & (drivers_license["Gender"]=="Female")]
df_license

License_Id  Age  Height Eye_Color Hair_Color  Gender Plate_Number  \
2291      291182   65      66      blue        Red  Female       08CM64   
4898      918773   48      65     black        Red  Female       917UU3   
6883      202298   68      66     green        Red  Female       500123   

     Car_Make Car_Model  
2291    Tesla   Model S  
4898    Tesla   Model S  
6883    Tesla   Model S

**_Al dataset "df_license" realizamos un merge con el dataset person para obtener la informacion de las personas_**

In [27]:
df_sospechoso_p = person.merge(df_license, on="License_Id")
df_sospechoso_p

Id              Name  License_Id  Address_Number Address_Street_Name  \
0  78881          Red Korb      918773             107         Camerata Dr   
1  90700     Regina George      291182             332           Maple Ave   
2  99716  Miranda Priestly      202298            1883          Golden Ave   

         Ssn  Age  Height Eye_Color Hair_Color  Gender Plate_Number Car_Make  \
0  961388910   48      65     black        Red  Female       917UU3    Tesla   
1  337169072   65      66      blue        Red  Female       08CM64    Tesla   
2  987756388   68      66     green        Red  Female       500123    Tesla   

  Car_Model  
0   Model S  
1   Model S  
2   Model S

**_Por ultimo realizamos un merger con el dataset que contiene la informacion de los eventos de diciembre del 2017_**

In [28]:
df_sospechoso_p = df_sospechoso_p.merge(df_facebook, left_on="Id", right_on="person_id")
df_sospechoso_p

Id              Name  License_Id  Address_Number Address_Street_Name  \
0  99716  Miranda Priestly      202298            1883          Golden Ave   
1  99716  Miranda Priestly      202298            1883          Golden Ave   
2  99716  Miranda Priestly      202298            1883          Golden Ave   

         Ssn  Age  Height Eye_Color Hair_Color  Gender Plate_Number Car_Make  \
0  987756388   68      66     green        Red  Female       500123    Tesla   
1  987756388   68      66     green        Red  Female       500123    Tesla   
2  987756388   68      66     green        Red  Female       500123    Tesla   

  Car_Model  person_id  event_id            event_name      date  
0   Model S      99716      1143  SQL Symphony Concert  20171206  
1   Model S      99716      1143  SQL Symphony Concert  20171212  
2   Model S      99716      1143  SQL Symphony Concert  20171229

## **_Con esto obtenemos el nombre del verdadero villano :)_**

In [29]:
from asesino import solucion
solucion("Miranda Priestly")

¡Muy bien hecho! Encontraste a la mente detras del asesinato
 Todos en Pandas City te aclaman como el mejor detective de PANDAS de todos los tiempos. ¡Ya es hora de sacar el champagne!
